### ISSUE TITLE
belgons_to assiciation drop down does not show when using simplemde editor

### ISSUE THREAD

**Issue by neidiom** [TrestleAdmin/trestle-simplemde#1]
belgons_to assiciation drop down does not show when using simplemde editor.

<img width="979" alt="screen shot 2018-08-12 at 07 02 02" src="https://user-images.githubusercontent.com/8058363/43998762-bcc00b9c-9dfd-11e8-96a1-4409cebd74a8.png">

**Comment by spohlenz** [comment]
Can you paste the contents of your Lessons admin file (`lessons_admin.rb`)?

**Comment by neidiom** [comment]
````
Trestle.resource(:lessons) do
  menu do
    item :lessons, icon: "fa fa-star"
  end

  form do |lessons|
    editor :description
  end
end
````

**Comment by spohlenz** [comment]
Okay, so once you start overriding the form block, you'll need to specify each field manually. For example, if your `Lesson` model has a `belongs_to :user`, you could add the select in like this:

```ruby
form do |lesson|
  select :user_id, User.all
  editor :description
end
```

**Comment by neidiom** [comment]
@spohlenz thanks, this works 👍
