### ISSUE TITLE
Content gets copied from previous lesson

### ISSUE THREAD

**Issue by neidiom** [TrestleAdmin/trestle-simplemde#2]
I have a Lesson model and when I try to add a new Lesson the content from previously saved Lesson gets copied to the new one.

**Comment by spohlenz** [comment]
I haven't been able to reproduce this issue directly. However I feel like it may be related to TrestleAdmin/trestle#123 which I have just fixed in `trestle-simplemde` 0.1.1. Could you please give that a try and see if it fixes your issue?
