### ISSUE TITLE
sassc-rails not listed as explicit dependency

### ISSUE THREAD

**Issue by airhorns** [TrestleAdmin/trestle-simplemde#3]
When adding `trestle-simplemde` to a Rails 6.0 app using Webpacker, `sassc-rails` is not an implicit or explicit dependency of the Rails app, and so the `scss` files in this gem fail to compile with `LoadError: cannot load such file -- sassc`

Adding `sassc-rails` to the app's Gemfile fixes the issue and lets the assets be built just fine which is good. Another option to fix this would be to switch to the newer style of precompiling the assets into plain ole JS for the trestle extensions. Any preference between the two fixes?

**Comment by spohlenz** [comment]
Given the simplicity of it, I've just rewritten the small amount of CSS from Sass to plain CSS with a Sprockets directive. This has been released as trestle-simplemde 0.1.2.
